"""add commitments table

Revision ID: 62dd5819e72f
Revises: a100f2adb92d
Create Date: 2026-08-27 22:48:26.308255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62dd5819e72f'
down_revision: Union[str, Sequence[str], None] = 'a100f2adb92d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commitments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('journal_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('binary', 'quota', 'numeric', 'journal', name='commitment_type'), nullable=False),
    sa.Column('cadence', sa.Enum('daily', 'weekly', name='commitment_cadence'), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('target_value', sa.Numeric(), nullable=True),
    sa.Column('comparator', sa.Enum('lte', 'gte', name='commitment_comparator'), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('active_from', sa.Date(), nullable=False),
    sa.Column('active_until', sa.Date(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_seq', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitments_change_seq'), 'commitments', ['change_seq'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commitments_change_seq'), table_name='commitments')
    op.drop_table('commitments')
    # ### end Alembic commands ###
