"""allow change_seq override for update bumping

Revision ID: b8b717e0518d
Revises: f5038f19746a
Create Date: 2026-08-29 01:07:11.724521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b717e0518d'
down_revision: Union[str, Sequence[str], None] = 'f5038f19746a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TABLES = ["goals", "commitments", "completions", "journals", "journal_entries"]


def upgrade() -> None:
    """Upgrade schema."""
    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ALTER COLUMN change_seq SET GENERATED BY DEFAULT")


def downgrade() -> None:
    """Downgrade schema."""
    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ALTER COLUMN change_seq SET GENERATED ALWAYS")
