from datetime import datetime

from sqlalchemy import BigInteger, DateTime, Identity, Table, event, func, text
from sqlalchemy.engine import Connection
from sqlalchemy.orm import DeclarativeBase, Mapped, Mapper, mapped_column


class Base(DeclarativeBase):
    pass


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)


class SyncMixin:
    # GENERATED BY DEFAULT (not ALWAYS): lets `_bump_change_seq` below assign an explicit
    # value on update, so a modified row sorts after every row that existed when it changed.
    change_seq: Mapped[int] = mapped_column(
        BigInteger, Identity(always=False), index=True, unique=True
    )


@event.listens_for(SyncMixin, "before_update", propagate=True)
def _bump_change_seq(mapper: Mapper[object], connection: Connection, target: object) -> None:
    if connection.dialect.name != "postgresql":
        return
    assert isinstance(mapper.local_table, Table)
    table_name = mapper.local_table.name
    new_seq = connection.execute(
        text("SELECT nextval(pg_get_serial_sequence(:table_name, 'change_seq'))"),
        {"table_name": table_name},
    ).scalar_one()
    target.change_seq = new_seq  # type: ignore[attr-defined]
